Exception created
iCloudBMX/DailyLeetcodeReminder pull request #4
Opened 2023-02-11 14:13 UTC by zuhriddinzayniddinov

2023-02-11 18:48 UTC, iCloudBMX requested changes

2023-02-11 18:48 UTC, iCloudBMX commented on .vscode/tasks.json
> +{
bu folderni ignore qiling

2023-02-11 18:48 UTC, iCloudBMX commented on .vscode/launch.json
> +{
Bu folderni ignore qiling

2023-02-11 18:48 UTC, iCloudBMX commented on src/DailyLeetcodeReminder.Core/Services/CommandHandler.cs
> +        catch(AlreadyExictException exception)
AlreadyExistsException bo'lishi kerak name

2023-02-11 18:48 UTC, iCloudBMX commented on src/DailyLeetcodeReminder.Core/Services/CommandHandler.cs
> +        catch(NotFaundLeetCodeUserNameException exception)
NotFoundException bo'lgani yaxshi

2023-02-11 18:48 UTC, iCloudBMX commented on src/DailyLeetcodeReminder.Core/Services/CommandHandler.cs
> +        catch(DuplicateTelegramIdException exception)
DuplicateUserException

2023-02-11 18:48 UTC, iCloudBMX commented on src/DailyLeetcodeReminder.Core/Services/CommandHandler.cs
> +        catch(DuplicateLeetCodeUserNameException exception)
Tepadagi exception yetadi

2023-02-11 18:48 UTC, iCloudBMX commented on src/DailyLeetcodeReminder.Core/Services/CommandHandler.cs
> +        catch(DuplicateLeetCodeUserNameException exception)
Exception larni user'ga yubormang bu xatolik, o'sha xatolikka mos xabar yuboring, error'lar saqlavchi birorta resource file tashkil qiling

2023-02-11 18:48 UTC, iCloudBMX commented on src/DailyLeetcodeReminder.Domain/Exceptions/AlreadyExict.cs
> +  public AlreadyExictException() :
Tepadagi muammolarni ko'rib chiqing

2023-02-12 04:02 UTC, zuhriddinzayniddinov commented on .vscode/tasks.json
> +{
Adashib ketib qolibti

2023-02-12 07:58 UTC, zuhriddinzayniddinov reviewed
I haven't tried running, but I think the logic is correct

2023-02-12 11:55 UTC, iCloudBMX approved these changes

2023-02-12 11:55 UTC, merged